# Travis CI for building ArgumentReader
# ----------------------------------------

language: csharp
solution: ArgumentsExtended.sln
mono: none
dotnet: 3.1.301

install: 
  - dotnet restore

script:
  - dotnet build --configuration Release
  - dotnet test
  - mkdir ./release
  - dotnet publish -c Release -o ./release --self-contained false
  - ls -l ./release
