# Travis CI for building ArgumentReader
# ----------------------------------------

language: csharp
solution: ArgumentsExtended.sln
mono: none
dotnet: 3.1.301

install: 
  - dotnet restore

script:
  - chmod 0777 ${TRAVIS_BUILD_DIR}/xcopy.bash
  - alias xcopy="${TRAVIS_BUILD_DIR}/xcopy.bash"
  - dotnet build
