# Travis CI for building ArgumentReader
# ----------------------------------------

language: csharp
solution: ArgumentsExtended.sln
mono: none
dotnet: 3.1.301

addons:
  apt:
    packages:
      - zip

install: 
  - dotnet restore

script:
  - dotnet build --configuration Release
  - dotnet test
  - mkdir ./release
  - dotnet publish -c Release -o ./release --self-contained false
  - ls -l ./release

befor_deploy:
  - zip -r ./release.zip ./release

deploy:
  privider: releases
  tag_name: latest
  override: true
  api_key: $GITHUB_TOKEN 
  file: "release.zip"
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
