# Travis CI for building ArgumentReader
# --------------------------------------------

language: csharp
solution: ArgumentsExtended.sln
mono: none
dotnet: 3.1.301

addons:
  apt:
    packages:
      - zip

install:
  - dotnet restore

script:
  - dotnet test

before_deploy:
  - dotnet build -c Release -o ./output
  - zip ArgumentReader.zip ./output/*Lib.dll

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file:
    - "./ArgumentReader.zip"
    - "./output/BooleanMarshalerLib.dll"
    - "./output/IntegerMarshalerLib.dll"
    - "./output/DoubleMarshalerLib.dll"
    - "./output/StringMarshalerLib.dll"
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - dotnet pack ./ArgumentsLib -c Release -o ./nuget
  - dotnet nuget push ./nuget/ArgumentsLib.*.nupkg -k $NUGET_ORG_KEY -s https://api.nuget.org/v3/index.json
  - rm -rf ./nuget
  - dotnet pack ./ArgumentMarshalerLib -c Release -o ./nuget
  - dotnet nuget push ./nuget/ArgumentMarshalerLib.*.nupkg -k $NUGET_ORG_KEY -s https://api.nuget.org/v3/index.json
